const Blogs = [
    {
      name: "Design",
      category: "design",
      Link: "/ux-design-glossary-guide",
      image: "/assets/blogs/featured/design-glossary.webp",
      description: "The UX Design Glossary: Deciphering the Alphabet Soup of UX Jargon",
    },
    {
      name: "Strategy",
      category: "strategy",
      Link: "/website-cost-guide",
      image: "/assets/blogs/featured/website-cost.webp",
      description: "How Much Should a Website Cost? Cracking the Ultimate Conundrum",
    },
    {
      name: "Design",
      category: "design",
      Link: "/how-to-choose-right-ux-agency",
      image: "/assets/blogs/featured/choose-right-ux-agency.webp",
      description: "How to Choose the Right UX Agency to Partner withfor Your Product Ideas",
    },
    {
      name: "Design",
      category: "design",
      Link: "/dark-ux-deceptive-design-practices",
      image: "/assets/blogs/featured/dark-ux-practice.webp",
      description: "Unmasking the Web's Dark Side: 5 Insider Secrets to Safeguard Your Site from Deceptive Design!",
    },
    {
      name: "Design",
      category: "design",
      Link: "/psychology-in-ux",
      image: "/assets/blogs/featured/psychology-in-ux.webp",
      description: "The Power of Psychology in UX Design: Unlocking the Human Element",
    },
    {
      name: "Design",
      category: "design",
      Link: "/experience-design-vs-ux",
      image: "/assets/blogs/featured/experience-design-vs-ux.webp",
      description: "What is Experience Design, And How is it Different from User Experience Design (UX)?",
      current: "active",
    },
  
    {
      name: "Marketing",
      category: "marketing",
      Link: "/top-digital-marketing-blogs",
      image: "/assets/blogs/featured/top-digital-marketing-blogs.webp",
      description: "Top 20 Digital Marketing Blogs to Follow for Expert Insights and Strategies",
    },
    {
      name: "Marketing",
      category: "marketing",
      Link: "/cognitive-biases-ecommerce",
      image: "/assets/blogs/featured/cognitive-biases-ecommerce.webp",
      description: "The Mind's Playground: 12 Cognitive Biases Ecommerce Marketers Need to Know",
    },
    {
      name: "Marketing",
      category: "marketing",
      Link: "/link-building-website-list",
      image: "/assets/blogs/featured/link-building.webp",
      description: "Beginners Guide to SEO: 30 websites to help you getting started on your link building journey",
    },
    {
      name: "Marketing",
      category: "marketing",
      Link: "/technical-seo-basics",
      image: "/assets/blogs/featured/technical-seo.webp",
      description: "A Beginner's Guide to Technical SEO",
    },
    {
      name: "Marketing",
      category: "marketing",
      Link: "/essential-link-building-guide",
      image: "/assets/blogs/featured/link-building-guide.webp",
      description: "A Beginner's Guide to Link Building",
    },
  
    {
      name: "Marketing",
      category: "marketing",
      Link: "/beginner-seo-guide",
      image: "/assets/blogs/featured/beginner-seo-guide.webp",
      description: "On-Page & Off-Page SEO: A Beginner's Guide to Optimizing Your Website",
    },
    {
      name: "Marketing",
      category: "marketing",
      Link: "/seo-keyword-research-guide",
      image: "/assets/blogs/featured/keyword-research-guide.webp",
      description: "Keyword Research: A Comprehensive Guide for SEO Success",
    },
    {
      name: "Marketing",
      category: "marketing",
      Link: "/basics-of-seo",
      image: "/assets/blogs/featured/basics-of-seo.webp",
      description: "The Basics of SEO: A Comprehensive Beginner's Guide",
    },
    {
      name: "Marketing",
      category: "marketing",
      Link: "/search-engines-mechanics",
      image: "/assets/blogs/featured/search-engines.webp",
      description: "How Search Engines Work: A Comprehensive Guide",
    },
    {
      name: "Marketing",
      category: "marketing",
      Link: "/benefits-of-organic-digital-marketing",
      image: "/assets/blogs/featured/search-engines.webp",
      description: "Organic Digital Marketing: The Game Changer Your Business Needs",
    },
    {
      name: "Marketing",
      category: "marketing",
      Link: "/boost-b2b-linkedin-strategies",
      image: "/assets/blogs/featured/b2b-linkedin.webp",
      description: "Turbocharge Your B2B LinkedIn Game with these 6 unbelievable strategies",
    },
    {
      name: "Marketing",
      category: "marketing",
      Link: "/power-remote-designers-india",
      image: "/assets/blogs/featured/remote-designers.webp",
      description: "Unleashing the Power of Remote Designers: Why Outsourcing to India is the Winning Move",
    },
  
    {
      name: "Marketing",
      category: "marketing",
      Link: "/captivate-audiences-marketing-psychology",
      image: "/assets/blogs/featured/captivate-audiences-marketing.webp",
      description: "Marketing Psychology: The Secret to Captivating Your Audience and Building Unforgettable Brands",
    },
    {
      name: "Marketing",
      category: "marketing",
      Link: "/future-of-marketing-neuromarketing",
      image: "/assets/blogs/featured/marketing-neuromarketing.webp",
      description: "The Future of Marketing: Why Every Marketer Should Learn Neuroscience and Master Neuromarketing",
    },
    {
      name: "Design",
      category: "design",
      Link: "/top-ux-design-blogs",
      image: "/assets/blogs/featured/ux-design-blogs.webp",
      description: "Top 20 UX Design Blogs to Follow for Innovative Ideas and Expert Insights",
    },
    {
      name: "Design",
      category: "design",
      Link: "/delightful-digital-design-guide",
      image: "/assets/blogs/featured/digital-design-guide.webp",
      description: "How to Delightfully Design for Diverse Digital Platforms: A User's Guide to Creative UX Mastery",
    },
    {
      name: "Design",
      category: "design",
      Link: "/evolution-of-ux-design",
      image: "/assets/blogs/featured/evolution-of-ux-design.webp",
      description: "The Evolution of UX Design: An Informative Expedition Through The History",
    },
    {
      name: "Design",
      category: "design",
      Link: "/what-is-ux-design",
      image: "/assets/blogs/featured/what-is-ux-design.webp",
      description: "What is UX Design: A Simple and Informative Guide for the Curious Minds",
    },
  ];

  export default Blogs;