export const projects = [
    {
        name: "Patronum",
        client: "Patronum",
        description: "Branding, Web Design, Marketing",
        src: "1.webp",
        year: 2023,
        link: "patronum-saas-case-study",
        srcSLider: "patronum.webp",
    },
    {
        name: "Dharan",
        client: "Dharan",
        description: "E-Commerce, Web Design, Development",
        src: "2.webp",
        year: 2023,
        link: "dharan-ecommerce-case-study",
        srcSLider: "dharan.webp",
    },
    {
        name: "Kedarkala",
        client: "Kedarkala",
        description: "Branding, Web Design",
        src: "3.webp",
        year: 2022,
        link: "kedarkala-portfolio-website-case-study",
        srcSLider: "kedarkala.webp",
    },
    {
        name: "Grand City Mall",
        client: "GCM",
        description: "Web Design, Development",
        src: "4.webp",
        year: 2022,
        link: "gcm-phygital-shopping-case-study",
        srcSLider: "gcm.webp",
    },
    {
        name: "Quick X",
        client: "Quick X",
        description: "Branding, Web Design, Marketing",
        src: "5.webp",
        year: 2023,
        link: "quickx-crypto-case-study",
        srcSLider: "quickx.webp",
    },
    {
        name: "Certvault",
        client: "Certvault",
        description: "UX Planning, UI Design",
        src: "6.webp",
        year: 2022,
        link: "certvault-case-study",
        srcSLider: "certvault.webp",
    },
    {
        name: "DMTCA",
        client: "DMTCA",
        description: "Branding, Web Design",
        src: "7-2.webp",
        year: 2022,
        link: "dmtca-digital-branding-case-study",
        srcSLider: "dmtca.webp",
    },
    {
        name: "PDTL",
        client: "PDTL",
        description: "Web Design, Branding, Development",
        src: "9.webp",
        year: 2022,
        link: "pdtl-ecommerce-automation-case-study",
        srcSLider: "pdtl.webp",
    },
    {
        name: "Wragby",
        client: "Wragby",
        description: "UI/UX Design, Web Design, Development",
        src: "10.webp",
        year: 2022,
        link: "wragby-solutions-case-study",
        srcSLider: "wragby.webp",
    },
    {
        name: "Patra",
        client: "Patra",
        description: "UX Planning, UI Design, Development",
        src: "8.webp",
        year: 2022,
        link: "patra-saas-insurtech-case-study",
        srcSLider: "patra.webp",
    },
]

