import React, { useEffect, useState, useLayoutEffect } from "react";
import Head from "next/head";
import Image from "next/image";
import { Cursor } from "../../cursor/index";
import "react-creative-cursor/dist/styles.css";
import { motion, AnimateSharedLayout, AnimatePresence } from "framer-motion";
import gsap from "gsap";
import { NextSeo } from "next-seo";

import Banner from "@/components/studio/Banner";
import Loader from "@/components/studio/Loader";
import StudioAero from "@/components/studio/StudioAero";
import WorkProject from "@/components/ProjectsSection/WorkProject";
import Slider from "@/components/studio/Slider";
import Footer from "@/components/Footer";
import Header from "@/components/Header/Header";
import SmoothScroll from "@/components/utils/SmoothScroll";
import FooterMobile from "@/components/Mobile/FooterMobile";
import ProjectWorks from "@/components/studio/ProjectWorks";
import WorksNextBox from "@/components/NextBoxes/WorksNextBox";

export default function studio() {
  const [loading, setLoading] = useState(true);

  useEffect(
    () => {
      loading
        ? document.querySelector("body").classList.add("loading")
        : document.querySelector("body").classList.remove("loading");
    },
    [loading],
    3000
  );

  // page Transition
  useEffect(() => {
    let ctx = gsap.context(() => {
      const tl = gsap.timeline();
      const svg = document.getElementById("svg");
      const curve = "M0, 502S175, 272, 500, 272s500, 230, 500, 230V0H0Z";
      const flat = "M0 2S175 1 500 1s500 1 500 1V0H0Z";

      tl.from(".loader-wrap-heading h1", {
        delay: 0.5,
        y: 200,
        skewY: 10,
      }).to(".loader-wrap-heading h1", {
        delay: 0.5,
        y: -200,
        skewY: 10,
      });
      tl.to(svg, {
        duration: 0.5,
        attr: { d: curve },
        ease: "power2.easeIn",
      }).to(svg, {
        duration: 0.5,
        attr: { d: flat },
        ease: "power2.easeOut",
      });
      tl.to(".loader-wrap", {
        y: -1500,
      });
      tl.to(".loader-wrap", {
        zIndex: -1,
        display: "none",
      });
    });
    return () => ctx.revert();
  }, []);

  return (
    <>

    <NextSeo
      title=""
      description="Generated by create next app"
      canonical="https://www.weareenigma.com/"
      openGraph={{
        url: "https://www.weareenigma.com/",
        title: "",
        description:
          "Generated by create next app",
        images: [
          {
            url: "",
            width: 400,
            height: 600,
            alt: "Enigma Image",
            type: "image/png",
          },
          { url: "" },
        ],
        siteName: "https://www.weareenigma.com/",
      }}
    />    

      <Head>
        <title>Portfolio | UI/UX Agency, Web Designing, Branding</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=5.0"
        ></meta>
        <link rel="icon" href="/fav-icon.png" />
      </Head>

      <Cursor isGelly={true} />

      <SmoothScroll />

      <div className="loader-wrap" id="loader" style={{ zIndex: 9999 }}>
        <svg viewBox="0 0 1000 1000" preserveAspectRatio="none">
          <path id="svg" d="M0,1005S175,995,500,995s500,5,500,5V0H0Z" />
        </svg>

        <div className="loader-wrap-heading">
          <span>
            <h1>Our Meticulously Crafted Projects</h1>
          </span>
        </div>
      </div>

      <div className="studio">
        <Header />
        <AnimatePresence>
          {loading ? (
            <motion.div key="loader">
              <Loader setLoading={setLoading} />
            </motion.div>
          ) : (
            <>
              <div data-cursor-size="10px" data-cursor-text="">
                <Banner />
              </div>
              {!loading && (
                <div className="transition-image final">
                  <motion.video
                    transition={{
                      ease: [0.6, 0.01, -0.05, 0.9],
                      duration: 1,
                    }}
                    src={`/assets/reels/showreel.mp4`}
                    loop
                    muted
                    autoPlay
                    layoutId="main-image-1"
                    data-cursor-text="Enigma"
                    data-cursor-size="100px"
                    data-cursor-color="#000"
                    className="studio-img-hero"
                  />
                </div>
              )}

              <section className="p-150" data-cursor-color="#000" data-cursor-size="0px">
                <StudioAero />
              </section>

               {/* ======================== Projects Slide ====================== */}
            <section className="desktop-projects m-150">
              <WorkProject />
            </section>

            <section className="mobile-projects">
              <ProjectWorks/>
            </section>

      {/* ======================== Projects Slide END ====================== */}

              <div className="pt-150">
                <Slider />
              </div>

              {/* Next Page Box */}
              <div className="m-150">
                <WorksNextBox />
              </div>
              {/* Next Page Box END */}

              {/* Footer */}
              <div className="desktop-footer">
                <Footer />
              </div>

              <div className="mobile-footer">
                <FooterMobile />
              </div>
              {/* Footer END */}
            </>
          )}
        </AnimatePresence>
      </div>
    </>
  );
}
